// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xipjymaznzviuyovmawk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcGp5bWF6bnp2aXV5b3ZtYXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTg0NTksImV4cCI6MjA2ODY5NDQ1OX0.Czax9yNhimTE_QY2JU_GT2wnBha6wIUqlzuhPMzdCd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});